apiVersion: v1
kind: Pod
metadata:
  name: kafka-server2
  labels:
    app: kafka
spec:
  containers:
    - name: kafka-server2
      image: confluentinc/cp-kafka:7.0.1
      ports:
        - containerPort: 9093
      env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:29093,PLAINTEXT_INTERNAL://kafka-server2:9093
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "FALSE"
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server2
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
