apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.1.7
      ports:
        - containerPort: 2181
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
